name: smoke
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - jupyterlab
  - statsmodels
  - scikit-learn
  - pip
  - pip:
      - pre-commit
      - nbstripout
